--[=[
    @class types

    Contains the miscellaneous types used in the documentation.
]=]

--------------------------------------------------------------------------------------------------------------------

--[=[
    @type table {[K] : V}
    @within types

    A table with keys of type `K` and values of type `V`.
]=]

--[=[
    @type list table<number, T>
    @within types

    A list with values of type `T`.
]=]

--[=[
    @type dict table<string, T>
    @within types

    A dictionary with keys of type `string` and values of type `T`.
]=]

--------------------------------------------------------------------------------------------------------------------